title: GEA Wiki
description: The where, when, what, and how of our department, for grad students.
theme: just-the-docs

url: https://ucalgea.github.io/docs

aux_links:
  Template Repository: https://github.com/uclaGEA/uclaGEA.github.io
