title: GEA Wiki
description: The where, when, what, and how of our department, for grad students.
theme: just-the-docs

url: https://ucalgea.github.io/docs

nav_external_links:
  - title: Return to GEA site
    url: https://uclagea.net
    hide_icon: false

aux_links:
    Repository:
        "https://github.com/uclaGEA/uclaGEA.github.io"

